headers_plaza_vea_csv = [
    'Competidor',
    'Categoría',
    'Subcategoría',
    'Sección',
    'Código Web Agrupado',
    'Código Web Individual',
    'EAN',
    'Descripción',
    'Marca',
    'UM',
    'Seller',
    'RUC',
    'Precio Regular',
    'Precio Promo',
    'Precio Tarjeta',
    'Página Web',
    'Delivery disponible',
    'Recojo en tienda',
    'Despacho a domicilio',
    'Shipping Cost',
    'Shipping Lead Time',
    'Delivery Time',
    'Tag Best Seller',
    'Stock',
    'Tiene Stock',
]

csv_paraiso_headers = [
    'competidor',
    'sección',
    'categoría',
    'subcategoría',
    'cod_web_agrupado',
    'cod_web_individual',
    'EAN',
    'descripción',
    'marca',
    'model',
    'line',
    'um',
    'seller',
    'precio_regular',
    'precio_promo',
    'precio_tarjeta',
    'pagina_web',
    'stock',
    'lead_time',
    'shipping_price',
    'breadcrumb',
    'colors',
    'existe_stock',
    'size'

]