headers_plaza_vea_csv = [
    'Competidor',
    'Categoría',
    'Subcategoría',
    'Sección',
    'Código Web Agrupado',
    'Código Web Individual',
    'EAN',
    'Descripción',
    'Marca',
    'UM',
    'Seller',
    'RUC',
    'Precio Regular',
    'Precio Promo',
    'Precio Tarjeta',
    'Página Web',
    'Delivery disponible',
    'Recojo en tienda',
    'Despacho a domicilio',
    'Shipping Cost',
    'Shipping Lead Time',
    'Delivery Time',
    'Tag Best Seller',
    'Stock',
    'Tiene Stock',
]

csv_paraiso_headers = [
    'Competidor',
    'Sección',
    'Categoría',
    'Subcategoría',
    'Código Web Agrupado',
    'cod_web_individual',
    'EAN',
    'Descripción',
    'Marca',
    'Model',
    'Line',
    'UM',
    'Seller',
    'Precio Regular',
    'Precio Promo',
    'Precio Tarjeta',
    'Página Web',
    'Stock',
    'Lead Time',
    'Shipping Cost',
    'Breadcrumb',
    'Colors',
    'Tiene Stock',
    'Tamaño'
]